package eosruntime

import (
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"m31labs.dev/eos/runtime/backend"
)

// TestPretrainedBERTGoldenFixtureParity checks the Go BERT-forward path
// against a committed Hugging Face reference (runtime/testdata/pretrained_bert_golden),
// so this parity gate always runs in CI, unlike TestPretrainedBERTHFParitySnapshot,
// which only runs when EOS_HF_BERT_PARITY_SNAPSHOT/EOS_HF_BERT_PARITY_PYTHON
// point at a full production HF snapshot and a Python oracle.
//
// The fixture is a tiny (~24KB), from-scratch, deterministically-seeded
// BertModel -- not a downloaded production model -- generated by
// runtime/testdata/pretrained_bert_golden/generate_fixture.py. Regenerate it
// with:
//
//	.venv-qwen3/bin/python3 runtime/testdata/pretrained_bert_golden/generate_fixture.py runtime/testdata/pretrained_bert_golden
func TestPretrainedBERTGoldenFixtureParity(t *testing.T) {
	dir := filepath.Join("testdata", "pretrained_bert_golden")
	golden := loadBERTGoldenFixture(t, filepath.Join(dir, "golden.json"))

	tokenizer, err := LoadHFWordPieceTokenizerFromDir(dir)
	if err != nil {
		t.Fatalf("load Go tokenizer: %v", err)
	}
	plan, err := PlanPretrainedBERTImportFromDir(dir, golden.ModelName)
	if err != nil {
		t.Fatalf("plan import: %v", err)
	}
	maxLength, pooling, err := bertParityReferenceSettings(plan)
	if err != nil {
		t.Fatalf("resolve reference settings: %v", err)
	}
	if maxLength != golden.MaxLength {
		t.Fatalf("resolved max_length = %d, want %d (golden fixture)", maxLength, golden.MaxLength)
	}
	if pooling != golden.Pooling {
		t.Fatalf("resolved pooling = %q, want %q (golden fixture)", pooling, golden.Pooling)
	}

	goInputIDs, goAttentionMask, goTokenTypeIDs := encodeBERTParityTexts(t, tokenizer, golden.Texts, maxLength)
	assertInt32SliceEqual(t, goInputIDs, golden.InputIDs)
	assertInt32SliceEqual(t, goAttentionMask, golden.AttentionMask)
	assertInt32SliceEqual(t, goTokenTypeIDs, golden.TokenTypeIDs)

	decoded, decodeReport, err := LoadPretrainedBERTDecodedWeightsFromDir(dir, plan)
	if err != nil {
		t.Fatalf("decode safetensors: %v", err)
	}
	if decodeReport.Status != "ok" {
		t.Fatalf("decode report status = %q", decodeReport.Status)
	}
	weights, weightReport, err := BuildPretrainedBERTWeightFileFromDecoded(decoded)
	if err != nil {
		t.Fatalf("build weight file: %v", err)
	}
	if weightReport.Status != "ok" {
		t.Fatalf("weight report status = %q", weightReport.Status)
	}
	mod, err := BuildPretrainedBERTEmbedderModule(plan)
	if err != nil {
		t.Fatalf("build embedder module: %v", err)
	}
	rt := New(bertEmbeddingHostBackend{})
	prog, err := rt.Load(context.Background(), mod, weights.LoadOptions()...)
	if err != nil {
		t.Fatalf("load embedder module: %v", err)
	}
	result, err := prog.Run(context.Background(), backend.Request{
		Entry: "bert_embed",
		Inputs: map[string]any{
			"input_ids":      backend.NewTensorI32([]int{len(golden.Texts), maxLength}, goInputIDs),
			"attention_mask": backend.NewTensorI32([]int{len(golden.Texts), maxLength}, goAttentionMask),
			"token_type_ids": backend.NewTensorI32([]int{len(golden.Texts), maxLength}, goTokenTypeIDs),
		},
	})
	if err != nil {
		t.Fatalf("run Go embedder: %v", err)
	}
	value, ok := result.Outputs["embeddings"]
	if !ok {
		t.Fatalf("missing embeddings output: %+v", result.Outputs)
	}
	got, ok := value.Data.(*backend.Tensor)
	if !ok {
		t.Fatalf("embedding output data type = %T, want *backend.Tensor", value.Data)
	}
	want := flattenPythonEmbeddings(golden.Embeddings)
	if gotLen, wantLen := len(got.F32), len(want); gotLen != wantLen {
		t.Fatalf("embedding value count = %d, want %d", gotLen, wantLen)
	}
	minCos, maxAbs := embeddingParityStats(got.F32, want, len(golden.Texts))
	t.Logf("BERT golden fixture parity: min_cosine=%.8f max_abs=%.8g tensors=%d", minCos, maxAbs, decodeReport.TensorCount)
	if minCos < 0.9999 || maxAbs > 2e-3 {
		t.Fatalf("embedding parity mismatch: min_cosine=%.8f want >= 0.9999; max_abs=%.8g want <= 0.002", minCos, maxAbs)
	}
}

type bertGoldenFixture struct {
	ModelName     string      `json:"model_name"`
	Pooling       string      `json:"pooling"`
	MaxLength     int         `json:"max_length"`
	Texts         []string    `json:"texts"`
	InputIDs      []int32     `json:"input_ids"`
	AttentionMask []int32     `json:"attention_mask"`
	TokenTypeIDs  []int32     `json:"token_type_ids"`
	Embeddings    [][]float32 `json:"embeddings"`
}

func loadBERTGoldenFixture(t *testing.T, path string) bertGoldenFixture {
	t.Helper()
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read golden fixture: %v", err)
	}
	var fixture bertGoldenFixture
	if err := json.Unmarshal(raw, &fixture); err != nil {
		t.Fatalf("parse golden fixture: %v", err)
	}
	if len(fixture.Texts) == 0 || len(fixture.Embeddings) == 0 {
		t.Fatalf("golden fixture is empty: %+v", fixture)
	}
	return fixture
}
